### ISSUE TITLE
Forgot to adjust comment on loess line in plots Aspect ratio (minor)

### ISSUE THREAD

**Issue by MMJansen** [royal-statistical-society/datavisguide#24]
On the page https://royal-statistical-society.github.io/datavisguide/docs/principles.html 
there is a comment line followed by a geom_smooth: 

`# Adding linear OLS regression fit of y~x. `
`gg <- gg + geom_smooth(method = "loess", color = "firebrick", se = FALSE)` 

Since the geom_smooth is not a linear OLS regression fit of y~x, I think you would want to adjust either the comment or the smooth. itself. Since the plot looks nice, it is probably the comment

**Comment by brtarran** [comment]
@andreas27 Are you able to respond to this issue, please?

**Comment by andreas27** [comment]
> @andreas27 Are you able to respond to this issue, please?

Fixed by adapting the comment to the code.
