### ISSUE TITLE
Graph missing a value label in the y-axis

### ISSUE THREAD

**Issue by star1327p** [royal-statistical-society/datavisguide#51]
In the section "Styling charts for RSS publications", the first graph has a missing "12" value label in the y-axis. 

The code `barplot(table(mtcars$gear), col = signif_blue)` needs revision to get a better display of the y-axis.

https://royal-statistical-society.github.io/datavisguide/docs/tools.html

**Comment by nrennie** [comment]
Great spot - thank you @star1327p! You've been added to the acknowledgements section of the guide: https://royal-statistical-society.github.io/datavisguide/about.html#acknowledgements

Thanks again!
